name: Build Image
on: workflow_dispatch
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: docker build image
      run: docker build -f dockerfile .
  
